Remove `*.mo` files from the repository.
zopefoundation/zope.app.locales pull request #18
Opened 2022-09-07 06:42 UTC by icemac

Fixes #7.

Document in the README how to generate `*.mo` files on the fly.

Fixes #17.

2022-09-07 10:14 UTC, mauritsvanrees requested changes
The mo files should not be in version control, so that part is good. The updated documentation is good.

But in my opinion the PyPI release *should* contain the compiled mo files. How? Install `zest.releaser` and `zest.pocompile` and run `fullrelease` Then the mo files get generated and included.
Well, `MANIFEST.in` would need `recursive-include src *.mo` otherwise they are not included after all.

See also https://github.com/zestsoftware/zest.pocompile

2022-09-08 06:15 UTC, icemac commented
@mauritsvanrees If I understood correctly, `zest.pocompile` has to be installed next to `zest.releaser`. I am using a globally installed `zest.releaser`. I can install `zest.pocompile` there. But is there a way to ensure that `zest.pocompile` is installed once I re-install `zest.releaser` in another environment and have forgotten that `zest.pocompile` should also be there?

2022-09-08 10:31 UTC, mauritsvanrees commented
I have not done this anywhere. But it is possible. cc @erral because this could be interesting for `plone.app.locales`: make sure running `fullrelease` fails when `zest.pocompile` is not installed. Let me check some options.

1. You could specify in `setup.cfg` that you want to use `zest.pocompile` and call it at the same time that it would normally run:

```
[zest.releaser]
releaser.after_checkout =
    zest.pocompile.compile.compile_in_tag
```

Then when you do not have it installed you get this error:

```
$ fullrelease
...
Traceback (most recent call last):
  File "/Users/maurits/zest.releaser/zest/releaser/utils.py", line 544, in resolve_name
    ret = getattr(ret, part)
AttributeError: module 'zest' has no attribute 'pocompile'
```

If you *do* have `zest.pocompile` installed, it will compile all po files that it finds. But after that, the *real* entry point is also triggered, and the po files are compiled *again*. So that is double work. Maybe `zest.releaser` should discover this corner case and only call it once.

And you only discover that you miss this package when you are halfway through the release. Preferably you would know it sooner.

2. Call it as the first hook:

```
[zest.releaser]
prereleaser.before =
    zest.pocompile.compile.compile_in_tag
```

This will give a warning:

    WARNING: Aborted compiling of po files: no tagdir found in data.

This is because this function is supposed to be called later, when the current working directory is in a clean temporary clone of the tag, which is what `zest.releaser` does right before uploading to PyPI.
The warning does no harm, but maybe you want to avoid it.

3. So call a different function in the beginning:

```
[zest.releaser]
prereleaser.before =
    zest.pocompile.compile.main
```

This will compile all po files that it finds.  That is actually a bit useless at this point though, because it does it on master. It should do it in the tag instead, as said. So this does not have an effect yet, except that it functions as a test that it works. And it does not take that long, so this could be a fine solution.

Alternatively, `zest.releaser` could suggest to authors of extensions to add a function `exists` or `require` or `available` that accepts a data dictionary as keyword arguments, and does completely nothing. You could use that then as a canary to check that the package is available. If that makes sense to you, I could do that in `zest.pocompile` now.

Otherwise, the third solution seems best to me.

2022-09-09 06:50 UTC, icemac commented
@mauritsvanrees Thank you for your suggestion. I implemented the third item and tried without and with having `zest.pocompile` installed: It works, the release now again contains the `*.mo`. Could you please re-review?

2022-09-09 10:47 UTC, mauritsvanrees commented on README.rst
> +translation files (``*.po``).
I would add: future versions will contain these files again.

2022-09-09 10:47 UTC, mauritsvanrees approved these changes

2022-09-09 10:48 UTC, mauritsvanrees commented
LGTM now. I added one small comment about documentation, but this PR can be merged with or without it.

2022-09-12 05:59 UTC, icemac commented on README.rst
> +translation files (``*.po``).
Fixed in https://github.com/zopefoundation/zope.app.locales/pull/18/commits/d114d5465eb305bd21633a0e9b359ad0c8cf2f73.

2022-09-12 06:00 UTC, merged